type Undefinedable<T> = T | undefined;
export type FunctionOnEnter = (currentState: string, nextState: string) => (void | Promise<void>);
export type FunctionOnLeave = (currentState: string, prevState: string) => (void | Promise<void>);
export type FunctionOnTransitionAfter = () => (void | Promise<void>);
export type FunctionOnTransitionBefore = () => (any | Promise<any>);
export type CheckAvailability = (path: string, hashPath: string, params?: {
    [key: string]: string;
}) => (boolean | Promise<boolean>);
export type RouteFunction = (path: string, hashPath: string, params?: {
    [key: string]: string;
}) => (void | Promise<void>);
declare class jFSMRouter {
    private static _instance;
    static get instance(): jFSMRouter;
    private _regexDuplicatePathId;
    private _regexSearchVariables;
    private _routes;
    private _routeFunction403;
    private _routeFunction404;
    private _routeFunction500;
    private _routing;
    private _queue;
    private _inTransition;
    private _currentState;
    private _states;
    private _transitions;
    private _window;
    private constructor();
    private static _CheckRouteEquivalence;
    stateAdd(state: string): boolean;
    stateDel(state: string): boolean;
    stateOnEnterAdd(state: string, func: FunctionOnEnter): boolean;
    stateOnEnterDel(state: string, func: FunctionOnEnter): boolean;
    stateOnLeaveAdd(state: string, func: FunctionOnLeave): boolean;
    stateOnLeaveDel(state: string, func: FunctionOnLeave): boolean;
    transitionAdd(from: string, to: string): boolean;
    transitionDel(from: string, to: string): boolean;
    transitionOnBeforeAdd(from: string, to: string, func: FunctionOnTransitionBefore): boolean;
    transitionOnBeforeDel(from: string, to: string, func: FunctionOnTransitionBefore): boolean;
    transitionOnAfterAdd(from: string, to: string, func: FunctionOnTransitionAfter): boolean;
    transitionOnAfterDel(from: string, to: string, func: FunctionOnTransitionAfter): boolean;
    get state(): Undefinedable<string>;
    stateSet(nextState: string): Promise<boolean>;
    checkTransition(nextState: string): boolean;
    routeSpecialAdd(code: number, routeFunction: RouteFunction): boolean;
    routeAdd(validState: string, path: string, routeFunction: RouteFunction, available?: CheckAvailability, routeFunction403?: RouteFunction): boolean;
    routeDel(path: string): boolean;
    trigger(path: string): void;
    route(path: string): Promise<void>;
    checkHash(): Promise<void>;
}
declare const _default: jFSMRouter;
export default _default;
